trivikr/vitest-codemod

.changeset/config.json, .changeset/nasty-comics-kick.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/bug_report_transform.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/feature_request_transform.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, .github/workflows/cache-cleanup-branch.yml, .github/workflows/lock.yml, .github/workflows/pull_request.yml, .github/workflows/push.yml, bin/vitest-codemod, package.json, pnpm-lock.yaml, src/cli.ts, src/transforms/index.ts, src/transforms/types.ts, src/utils/getHelpParagraph.ts, src/utils/getJsCodeshiftParser.ts, src/utils/getTransformDescription.ts, src/utils/getTransforms.ts, src/utils/getUpdatedTransformFile.ts, src/utils/index.ts, tsconfig.json
=> Add initial code

.github/workflows/push.yml
We moved to a monorepo in https://github.com/trivikr/vitest-codemod/pull/5
A release now can have multiple versions
Use default title from changesets
CI
=> Use default title from changesets

.changeset/config.json, package.json, yarn.lock
N/A
Uses the changelog format used by changesets package
https://github.com/changesets/changesets/blob/8447c677a37d1d23858059e0ce2b5cd98f4c24ae/.changeset/config.json#LL2C16-L5C5
Will be tested in https://github.com/trivikr/vitest-codemod/pull/9
=> Use changelog format from @changesets/changelog-github

packages/vitest-codemod/CHANGELOG.md
Use CHANGELOG formatting in https://github.com/trivikr/vitest-codemod/pull/9
Update CHANGELOG to use @changesets/changelog-github
=> Update CHANGELOG to use @changesets/changelog-github

package.json
Refs: https://github.com/changesets/action/issues/170#issuecomment-1092270826
Attempts to fix revert done due to build failure https://github.com/trivikr/vitest-codemod/pull/13
We'll verify if yarn.lock gets updated in https://github.com/trivikr/vitest-codemod/pull/14
Refs: https://github.com/changesets/action/issues/170#issuecomment-1092270826
=> Update yarn.lock on release

package.json
Refs: https://github.com/ts-plus/stdlib/commit/06d313a764c05766cb7f006bf26fa5998edbff38
Runs yarn --no-immutable in version command
Will verify after publish that lockfile gets updated in https://github.com/trivikr/vitest-codemod/pull/16
=> Run yarn --no-immutable in version command

.changeset/slow-plants-buy.md, packages/jest/README.md, packages/jest/package.json, packages/jest/src/index.ts, packages/jest/src/transform.ts, packages/jest/src/transformer.ts, packages/jest/tsconfig.json, yarn.lock
N/A
Adds basic source code for @vitest-codemod/jest 
* The transform details are in `index.ts`
* The transformer is in `transformer.ts`
Will be done when `@vitest-codemod/jest` is imported in `vitest-codemod`
=> Add basic source code for @vitest-codemod/jest

packages/vitest-codemod/package.json
N/A
Removes redundant keys from package.json
CI
=> chore(codemod): remove redundant keys from package.json

.changeset/config.json
N/A
Updates internal dependents in changesets
Will verify post merge that vitest-codemod@0.0.4 is released in https://github.com/trivikr/vitest-codemod/pull/21
* Used in changesets repo https://github.com/changesets/changesets/blob/main/.changeset/config.json
* Docs: https://github.com/changesets/changesets/blob/main/docs/experimental-options.md
=> chore(workflow): updateInternalDependents in changesets

.eslintrc, .vscode/settings.json, package.json, yarn.lock
N/A
Enable eslint with setup from vitest
Code will be edited in future PRs
=> Enable eslint

package.json, tsconfig.json
Missed in https://github.com/trivikr/vitest-codemod/pull/34
Run eslint at top-level
N/A
=> Run eslint at top-level

.github/workflows/build.yml, package.json, packages/jest/package.json, packages/types/package.json, packages/vitest-codemod/package.json
N/A
Add test script in packages with exit 0
* CI is successful.
* Tests will be added in future PRs, like https://github.com/trivikr/vitest-codemod/pull/39
=> Add test script in packages with exit 0

package.json
N/A
Pass --versbose in build/test scripts, so that output can be examined
CI
=> Pass --versbose in build/test scripts

.eslintrc, package.json, packages/jest/jest.config.json, packages/jest/package.json, packages/jest/src/__fixtures__/basic.input.js, packages/jest/src/__fixtures__/basic.output.js, vitest.config.ts, yarn.lock
N/A
Adds basic tests and runs them
CI
=> chore(jest): add basic tests and run them

packages/vitest-codemod/README.md
Add example missed in https://github.com/trivikr/vitest-codemod/pull/42
Add example of a transform in README.md
N/A
=> Add example in README.md

packages/jest/package.json
Requirement noticed in https://github.com/trivikr/vitest-codemod/pull/49
Docs: https://jestjs.io/docs/ecmascript-modules
Run jest with experimental-vm-modules
CI
=> Run jest with experimental-vm-modules

.changeset/silent-countries-repeat.md, packages/jest/src/__fixtures__/replace-jest-imports.input.mjs, packages/jest/src/__fixtures__/replace-jest-imports.output.mjs, packages/jest/src/transformer.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/50
Replace explicit jest global imports
CI
=> Replace explicit jest global imports

packages/jest/package.json
N/A
Adds test:jest script to simplify running jest tests
CI
=> Add test:jest script

packages/jest/src/__fixtures__/test/test-concurrent-each.input.js, packages/jest/src/__fixtures__/test/test-concurrent-each.output.js, packages/jest/src/__fixtures__/test/test-concurrent-only-each.input.js, packages/jest/src/__fixtures__/test/test-concurrent-only-each.output.js, packages/jest/src/__fixtures__/test/test-concurrent-skip-each.input.js, packages/jest/src/__fixtures__/test/test-concurrent-skip-each.output.js, packages/jest/src/__fixtures__/test/test-only.input.js, packages/jest/src/__fixtures__/test/test-only.output.js, packages/jest/src/__fixtures__/test/test-todo.input.js, packages/jest/src/__fixtures__/test/test-todo.output.js
Noticed in https://github.com/trivikr/vitest-codemod/pull/64
Updates describe name to that of file name
CI
=> Update describe name to that of file name

packages/jest/src/__fixtures__/test/test-fails-each.input.js, packages/jest/src/__fixtures__/test/test-fails-each.output.js, packages/jest/src/__fixtures__/test/test-fails.input.js, packages/jest/src/__fixtures__/test/test-fails.output.js, packages/jest/src/__fixtures__/test/test-only-each.input.js, packages/jest/src/__fixtures__/test/test-only-each.output.js, packages/jest/src/__fixtures__/test/test-only-fails.input.js, packages/jest/src/__fixtures__/test/test-only-fails.output.js, packages/jest/src/__fixtures__/test/test-only.input.js, packages/jest/src/__fixtures__/test/test-only.output.js, packages/jest/src/__fixtures__/test/test-skip-each.input.js, packages/jest/src/__fixtures__/test/test-skip-each.output.js, packages/jest/src/__fixtures__/test/test-skip.input.js, packages/jest/src/__fixtures__/test/test-skip.output.js
Noticed while working on https://github.com/trivikr/vitest-codemod/pull/68
Adds tests into separate files.
This allows testing imports from MemberExpression
CI
=> Add tests into separate files

.changeset/fuzzy-crabs-walk.md, packages/jest/src/__fixtures__/test/fit-each.input.js, packages/jest/src/__fixtures__/test/fit-each.output.js, packages/jest/src/__fixtures__/test/fit-fails.input.js, packages/jest/src/__fixtures__/test/fit-fails.output.js, packages/jest/src/__fixtures__/test/fit.input.js, packages/jest/src/__fixtures__/test/fit.output.js, packages/jest/src/apis/getApisFromCallExpression.ts, packages/jest/src/apis/getApisFromMemberExpression.ts, packages/jest/src/apis/index.ts, packages/jest/src/apis/replaceTestApiFit.ts, packages/jest/src/transformer.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/67
Support transformation of `fit` to `it.only`
CI
=> Support transformation of `fit` to `it.only`

.changeset/proud-insects-vanish.md, packages/jest/src/__fixtures__/describe/decribe-each.input.js, packages/jest/src/__fixtures__/describe/decribe-each.output.js, packages/jest/src/__fixtures__/describe/describe-only-each.input.js, packages/jest/src/__fixtures__/describe/describe-only-each.output.js, packages/jest/src/__fixtures__/describe/describe-only.input.js, packages/jest/src/__fixtures__/describe/describe-only.output.js, packages/jest/src/__fixtures__/describe/describe-skip-each.input.js, packages/jest/src/__fixtures__/describe/describe-skip-each.output.js, packages/jest/src/__fixtures__/describe/describe-skip.input.js, packages/jest/src/__fixtures__/describe/describe-skip.output.js, packages/jest/src/apis/getApisFromMemberExpression.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/71
Support member expressions from describe
CI
=> Import describe when member expression is used in jest

packages/jest/src/__fixtures__/snapshot/__snapshots__/addSnapshotSerializer.input.js.snap, packages/jest/src/__fixtures__/snapshot/__snapshots__/addSnapshotSerializer.output.js.snap, packages/jest/src/__fixtures__/snapshot/__snapshots__/toMatchSnapshot.input.js.snap, packages/jest/src/__fixtures__/snapshot/__snapshots__/toMatchSnapshot.output.js.snap, packages/jest/src/__fixtures__/snapshot/addSnapshotSerializer.input.js, packages/jest/src/__fixtures__/snapshot/addSnapshotSerializer.output.js, packages/jest/src/__fixtures__/snapshot/toMatchInlineSnapshot.input.js, packages/jest/src/__fixtures__/snapshot/toMatchInlineSnapshot.output.js, packages/jest/src/__fixtures__/snapshot/toMatchSnapshot.input.js, packages/jest/src/__fixtures__/snapshot/toMatchSnapshot.output.js
Closes https://github.com/trivikr/vitest-codemod/issues/84
Add test for Snapshot testing
CI
=> Add test for Snapshot testing

.changeset/old-hats-fetch.md, packages/jest/src/__fixtures__/mock/disableAutomock.error.js, packages/jest/src/__fixtures__/mock/enableAutomock.error.js, packages/jest/src/apis/replaceJestObjectWithVi.ts, packages/jest/src/transformer.spec.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/90
Throws error on encountering automocking APIs
CI
=> Throw error on encountering automocking APIs

package.json, yarn.lock
=> Bump vitest to 0.28.4

.changeset/good-squids-relax.md, packages/jest/src/__fixtures__/mock/createMockFromModule.input.js, packages/jest/src/__fixtures__/mock/createMockFromModule.output.js, packages/jest/src/__fixtures__/mock/getTokenModule.js, packages/jest/src/apis/replaceJestObjectWithVi.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/94
Add transformation for jest.createMockFromModule
CI
=> Add transformation for jest.createMockFromModule

.changeset/empty-bananas-shake.md, packages/jest/src/__fixtures__/mock/requireMock.input.js, packages/jest/src/__fixtures__/mock/requireMock.output.js, packages/jest/src/apis/replaceJestObjectWithVi.ts
Follow-up to https://github.com/trivikr/vitest-codemod/pull/95
Add transformation for jest.requireMock
CI
=> Add transformation for jest.requireMock

.changeset/tender-drinks-lay.md, packages/jest/src/__fixtures__/mock/requireActual.input.js, packages/jest/src/__fixtures__/mock/requireActual.output.js, packages/jest/src/apis/replaceJestObjectWithVi.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/83
Add transformation for jest.requireActual
CI
=> Add transformation for jest.requireActual

.changeset/cyan-deers-allow.md
Creates changeset for releasing:
* https://github.com/trivikr/vitest-codemod/pull/95
* https://github.com/trivikr/vitest-codemod/pull/98
* https://github.com/trivikr/vitest-codemod/pull/99
Support Jest APIs which become async in Vitest
CI
=> Support Jest APIs which change to async in Vitest

packages/jest/src/__fixtures__/expect/lastCalledWith.input.js, packages/jest/src/__fixtures__/expect/lastCalledWith.output.js, packages/jest/src/__fixtures__/expect/nthCalledWith.input.js, packages/jest/src/__fixtures__/expect/nthCalledWith.output.js, packages/jest/src/__fixtures__/expect/toBeCalled.input.js, packages/jest/src/__fixtures__/expect/toBeCalled.output.js, packages/jest/src/__fixtures__/expect/toBeCalledTimes.input.js, packages/jest/src/__fixtures__/expect/toBeCalledTimes.output.js, packages/jest/src/__fixtures__/expect/toBeCalledWith.input.js, packages/jest/src/__fixtures__/expect/toBeCalledWith.output.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalled.input.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalled.output.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalledTimes.input.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalledTimes.output.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalledWith.input.js, packages/jest/src/__fixtures__/expect/toHaveBeenCalledWith.output.js, packages/jest/src/__fixtures__/expect/toHaveBeenLastCalledWith.input.js, packages/jest/src/__fixtures__/expect/toHaveBeenLastCalledWith.output.js, packages/jest/src/__fixtures__/expect/toHaveBeenNthCalledWith.input.js, packages/jest/src/__fixtures__/expect/toHaveBeenNthCalledWith.output.js
N/A
Add expect tests for mock functions
CI
=> Add expect tests for mock functions returned

packages/jest/src/__fixtures__/expect/lastReturnedWith.input.js, packages/jest/src/__fixtures__/expect/lastReturnedWith.output.js, packages/jest/src/__fixtures__/expect/nthReturnedWith.input.js, packages/jest/src/__fixtures__/expect/nthReturnedWith.output.js, packages/jest/src/__fixtures__/expect/toHaveLastReturnedWith.input.js, packages/jest/src/__fixtures__/expect/toHaveLastReturnedWith.output.js, packages/jest/src/__fixtures__/expect/toHaveNthReturnedWith.input.js, packages/jest/src/__fixtures__/expect/toHaveNthReturnedWith.output.js, packages/jest/src/__fixtures__/expect/toHaveReturned.input.js, packages/jest/src/__fixtures__/expect/toHaveReturned.output.js, packages/jest/src/__fixtures__/expect/toHaveReturnedTimes.input.js, packages/jest/src/__fixtures__/expect/toHaveReturnedTimes.output.js, packages/jest/src/__fixtures__/expect/toHaveReturnedWith.input.js, packages/jest/src/__fixtures__/expect/toHaveReturnedWith.output.js, packages/jest/src/__fixtures__/expect/toReturn.input.js, packages/jest/src/__fixtures__/expect/toReturn.output.js, packages/jest/src/__fixtures__/expect/toReturnTimes.input.js, packages/jest/src/__fixtures__/expect/toReturnTimes.output.js, packages/jest/src/__fixtures__/expect/toReturnWith.input.js, packages/jest/src/__fixtures__/expect/toReturnWith.output.js
N/A
Add expect tests which check for returned values
CI
=> Add expect tests which check for returned values

packages/jest/src/__fixtures__/returns/toHaveReturned.input.js, packages/jest/src/__fixtures__/returns/toHaveReturned.output.js, packages/jest/src/__fixtures__/returns/toReturn.input.js, packages/jest/src/__fixtures__/returns/toReturn.output.js
Issue https://github.com/vitest-dev/vitest/issues/2849 is fixed, and released in https://github.com/vitest-dev/vitest/releases/tag/v0.28.5
Uncomment checks for toHaveReturned tests
CI
=> Uncomment checks for toHaveReturned tests

.changeset/empty-needles-complain.md, packages/jest/src/__fixtures__/mock/genMockFromModule.input.js, packages/jest/src/__fixtures__/mock/genMockFromModule.output.js, packages/jest/src/apis/replaceJestObjectWithVi.ts
Refs: https://github.com/trivikr/vitest-codemod/issues/94
Add transformation for jest.genMockFromModule
CI
=> Add transformation for jest.genMockFromModule

.changeset/popular-hounds-deliver.md, packages/jest/src/__fixtures__/mock/setMock-default.input.js, packages/jest/src/__fixtures__/mock/setMock-default.output.js, packages/jest/src/__fixtures__/mock/setMock-named.input.js, packages/jest/src/__fixtures__/mock/setMock-named.output.js, packages/jest/src/apis/addFactoryFunctionToMock.ts, packages/jest/src/apis/index.ts, packages/jest/src/apis/replaceJestObjectWithVi.ts, packages/jest/src/apis/updateDefaultExportMocks.ts, packages/jest/src/transformer.ts
Fixes: https://github.com/trivikr/vitest-codemod/issues/121
Support transformation for jest.setMock
CI
=> Support transformation for jest.setMock

.changeset/spotty-pumpkins-repair.md, packages/jest/src/__fixtures__/mock/deepUnmock.input.js, packages/jest/src/__fixtures__/mock/deepUnmock.output.js, packages/jest/src/apis/replaceJestObjectWithVi.ts
Refs: https://jestjs.io/docs/jest-object#jestdeepunmockmodulename
Add transformation for jest.deepUnmock
CI
=> Add transformation for jest.deepUnmock

packages/jest/src/__fixtures__/mock/doMock.input.js, packages/jest/src/__fixtures__/mock/doMock.output.js
Refs: https://github.com/vitest-dev/vitest/issues/2870
Add test for mock/doMock
CI
=> Add test for mock/doMock

packages/jest/package.json, yarn.lock
Test fixes like in https://github.com/facebook/jest/issues/13808
Bump jest to v29.4.3
CI
=> Bump jest to v29.4.3

packages/types/package.json, packages/vitest-codemod/package.json
Fixes: https://github.com/trivikr/vitest-codemod/issues/129
Remove redundant test scripts
CI
=> Remove redundant test scripts

packages/jest/src/__fixtures__/mock/mockReturnThis.input.js, packages/jest/src/__fixtures__/mock/mockReturnThis.output.js
Refs: https://jestjs.io/docs/mock-function-api#mockfnmockreturnthis
Add test for mock/mockReturnThis
CI
=> Add test for mock/mockReturnThis
