.changeset/dry-trees-brush.md
packages/types/README.md
packages/types/package.json
packages/types/src/index.ts
packages/types/src/transform.ts
packages/types/tsconfig.json
tsconfig.json
yarn.lock

Adds source code for @vitest-codemod/types
This would replace the types in transforms folder in vitest-codemod

Add source code for @vitest-codemod/types

---

.changeset/dry-trees-brush.md
.changeset/fair-pants-travel.md
packages/types/CHANGELOG.md
packages/types/package.json
packages/vitest-codemod/CHANGELOG.md
packages/vitest-codemod/package.json

This reverts commit 95b3e725661ad276f170cbf838b56200aea9b007.
Yarn lockfile is not updated, resulting in release failure in https://github.com/trivikr/vitest-codemod/actions/runs/4039762104/jobs/6944796438
Revert "Version Packages (#9)"
CI

Revert "Version Packages (#9)"

---

.github/workflows/push.yml
package.json

Refs: https://github.com/changesets/action/issues/170#issuecomment-1092270826
Runs yarn after changeset version, so that lockfile can be updated
Will verify after publish that lockfile gets updated in https://github.com/trivikr/vitest-codemod/pull/16

Run yarn after changeset version

---

package.json

Noticed in CI failures in https://github.com/trivikr/vitest-codemod/pull/19
Follow toplogical-dev order when building packages.
This way, the devDependency `@vitest-codemod/types` will be built prior to module `@vitest-codemo/jest`
CI

Follow topological-dev order when building packages

---

.changeset/five-adults-report.md
packages/vitest-codemod/package.json
packages/vitest-codemod/src/utils/getTransforms.ts
yarn.lock

N/A
Display help from @vitest-codemod/jest
```console
$ ./bin/vitest-codemod --help | head
-----------------------------------------------------------------------------------------------
vitest-codemod is a lightweight wrapper over jscodeshift.
It processes --help, --version and --transform options before passing them downstream.
You can provide names of the custom transforms instead of a local path or url:
jest  Converts Jest APIs in a Javascript/TypeScript codebase to Vitest 
Example: vitest-codemod -t jest example.spec.js
```

chore(codemod): display help from @vitest-codemod/jest

---

.changeset/modern-tigers-repeat.md
packages/jest/package.json
packages/vitest-codemod/package.json
yarn.lock

Workspace protocol is not supported by changesets/action:
* https://github.com/changesets/action/issues/95
* https://github.com/changesets/action/issues/172
* https://github.com/changesets/action/issues/246
This results in following error thrown:
```console
$ npx vitest-codemod@0.0.4 --version
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.0.1
```
Remove "workspace:" protocol for internal dependencies
Will be verified after publish

Remove "workspace:" protocol for internal dependencies

---

.changeset/modern-pillows-leave.md
packages/vitest-codemod/src/utils/getUpdatedTransformFile.ts

N/A
Returns updated transform file path
Verified that filepath was printed on using console.log, and transformation was run
```console
$ ./bin/vitest-codemod -t jest example.js
{
filePath: '/Users/trivikram/workspace/vitest-codemod/packages/jest/dist/transformer.js'
}
Skipping path example.js which does not exist. 
No files selected, nothing to do. 
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
```

Return updated transform file path

---

.changeset/weak-planets-remain.md
packages/jest/src/transformer.ts
packages/vitest-codemod/src/utils/getJsCodeshiftParser.ts

Refs:
* https://github.com/facebook/jscodeshift/issues/488
* https://github.com/facebook/jscodeshift/issues/500
The jscodeshift a parser parameter defaults to `babel5compat`, which is has a significantly reduced feature set from ts, babylon, etc. The upstream project is meaning to switch default parser to babylon.
N/A

Default parser to babylon

---

package.json
packages/jest/package.json
packages/types/package.json
packages/vitest-codemod/package.json
yarn.lock

Refs: https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces
Runs global version of tsc from packages. This way, the typescript dependency needs to be defined only at root level.
CI

Run global version of tsc from packages

---

package.json
yarn.lock

Follow-up to https://github.com/trivikr/vitest-codemod/pull/34
Run eslint on precommit
Verified that eslint is run on precommit
```console
$ git diff
diff --git a/packages/vitest-codemod/src/cli.ts b/packages/vitest-codemod/src/cli.ts
index 993dd96..6034d27 100644
--- a/packages/vitest-codemod/src/cli.ts
+++ b/packages/vitest-codemod/src/cli.ts
@@ -5,8 +5,8 @@
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
-import path from 'path'
import Runner from 'jscodeshift/dist/Runner'
+import path from 'path'
import {
getHelpParagraph,
$ git add .
$ git commit -m test
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✖ Prevented an empty git commit!
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...
⚠ lint-staged prevented …
```

Run eslint on precommit

---

.github/workflows/build.yml
package.json
packages/vitest-codemod/src/cli.ts

Follow-up to https://github.com/trivikr/vitest-codemod/pull/36
Runs lint before build in CI
Verified that CI fails in case of linting error in https://github.com/trivikr/vitest-codemod/actions/runs/4049926689/jobs/6966819696

Run lint before build in CI

---

.changeset/shy-lizards-poke.md

Transform to add vitest imports for jest globals was added in https://github.com/trivikr/vitest-codemod/pull/42
Bump to 0.1.0 as basic transform to support jest has landed
CI

Bump to 0.1.0 as basic transform to support jest has landed

---

packages/jest/src/transformer.ts

Production code in other codemods use getter
Example: https://github.com/deconstructionalism/generator-redux-logic/blob/86bc1abeeb20bf730d2b98d5b3db39c14a12d53a/generators/reducer/index.js#L111
Use getter for adding import declaration
CI

Use getter for adding import declaration

---

packages/jest/jest.config.json
packages/jest/src/transformer.spec.ts
vitest.config.ts

Requirement was noticed in https://github.com/trivikr/vitest-codemod/pull/49
Support running tests from `*.mjs` files
CI

Support running tests from *.mjs files

---

tsconfig.build.json

N/A
Exclude dist, __fixtures__ and *.spec.ts in root TSConfig
Verified that transformer.spec.ts is not compiled by TypeScript

Exclude dist, __fixtures__ and *.spec.ts in root TSConfig

---

.changeset/orange-pianos-count.md
packages/jest/src/__fixtures__/test/test-fails.input.js
packages/jest/src/__fixtures__/test/test-fails.output.js
packages/jest/src/__fixtures__/test/test-only-fails.input.js
packages/jest/src/__fixtures__/test/test-only-fails.output.js
packages/jest/src/__fixtures__/test/test-skip-fails.input.js
packages/jest/src/__fixtures__/test/test-skip-fails.output.js
packages/jest/src/apis/getApisFromMemberExpression.ts
packages/jest/src/apis/index.ts
packages/jest/src/apis/replaceTestApiFailing.ts
packages/jest/src/transformer.ts

Fixes: https://github.com/trivikr/vitest-codemod/issues/63
Support transformation of `.failing` to `.fails`
CI

Support transformation of `.failing` to `.fails`

---

package.json
yarn.lock

N/A
Vite is not needed to use vitest
https://vitest.dev/guide/#adding-vitest-to-your-project
CI

chore(deps-dev): remove vite as vitest has it in-built

---

packages/jest/package.json
yarn.lock

Noticed in https://github.com/trivikr/vitest-codemod/pull/76 that @types/jest are missing
Add '@types/jest' devDependency
CI

Add '@types/jest' devDependency

---

.changeset/late-cameras-kiss.md
packages/jest/src/__fixtures__/misc/with-existing-imports.input.mjs
packages/jest/src/__fixtures__/misc/with-existing-imports.output.mjs
packages/jest/src/__fixtures__/misc/with-file-headers.input.js
packages/jest/src/__fixtures__/misc/with-file-headers.output.js
packages/jest/src/__fixtures__/misc/with-top-jsdoc-comment.input.js
packages/jest/src/__fixtures__/misc/with-top-jsdoc-comment.output.js
packages/jest/src/__fixtures__/misc/with-top-line-comment.input.js
packages/jest/src/__fixtures__/misc/with-top-line-comment.output.js
packages/jest/src/modules/index.ts
packages/jest/src/modules/prependImport.ts
packages/jest/src/transformer.ts

Previously, `vitest` imports would get prepended to the very top of the file regardless of whether there was a file-level header, which meant the import would often appear above the comment. This makes two changes:
1. If there are existing imports, move the comment node attached to the first import (if any) to the new, prepended import
2. If there are no existing imports, move the first comment to the inserted import if it looks like a file-level comment (not a line comment, not a JSDoc comment)
Added test fixtures
Thanks for building this repo!

Preserve file comments when prepending import

---

package.json
yarn.lock

Release https://github.com/vitest-dev/vitest/releases/tag/v0.28.5
Bump vitest to v0.28.5
CI

Bump vitest to v0.28.5

---

packages/jest/src/__fixtures__/expect/toHaveProperty.input.js
packages/jest/src/__fixtures__/expect/toHaveProperty.output.js

Issue https://github.com/vitest-dev/vitest/issues/2804 is fixed, and released in https://github.com/vitest-dev/vitest/releases/tag/v0.28.5
Uncomment test for toHaveProperty with number in keyPath array
CI

Uncomment test for toHaveProperty with number in keyPath array

---

.changeset/hot-kiwis-help.md
packages/jest/src/__fixtures__/mock/disableAutomock.error.js
packages/jest/src/__fixtures__/mock/disableAutomock.input.js
packages/jest/src/__fixtures__/mock/disableAutomock.output.js
packages/jest/src/apis/getApisFromMemberExpression.ts
packages/jest/src/apis/replaceJestObjectWithVi.ts

Fixes: https://github.com/trivikr/vitest-codemod/issues/111
Delete jest.disableAutomock() as vitest does not mock by default
CI

Delete jest.disableAutomock() as vitest does not mock by default

---

.changeset/big-geckos-give.md
packages/jest/src/apis/replaceJestObjectWithVi.ts

Follow-up to https://github.com/trivikr/vitest-codemod/issues/111
Add link to migration guide in the error on jest.enableAutomock()
CI

Add link to migration guide in the error on jest.enableAutomock()
